steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}'
      - '--build-arg'
      - 'NEXT_PUBLIC_SITE_URL=${_NEXT_PUBLIC_SITE_URL}'
      - '-t'
      - '${_IMAGE}'
      - '.'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', '${_IMAGE}']
images:
  - '${_IMAGE}'
options:
  logging: CLOUD_LOGGING_ONLY
